#!/usr/bin/env python3

import sys

# necessary on some system due to a qt5 bug
import PyKDL

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone='dynamic_stack_decider_visualization.dsd_visualization_plugin.DsdVizPlugin'))
